# basic options
title: PhD Student: Machine Learning Researcher 
author: James O' Neill
email: jamesoneill1258@gmail.com
description: Personal Site
twitter_username: JamesONeil21
github_username:  jamesoneill12

# Build settings
markdown: kramdown
theme: minima
